global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"
  
scrape_configs:
  - job_name: rabbitmq
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'keydb'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:3000']
